name: Build and Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas 
      - name: Checkout Azure Resource Manager Template Toolkit
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk 
      - name: Checkout arm-oraclelinux-wls
        uses: actions/checkout@v2
        with:
          path: arm-oraclelinux-wls
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Built and test arm-oraclelinux-wls
        run: mvn -Ptemplate-validation-tests clean install --file arm-oraclelinux-wls/pom.xml  
        
      - name: Get version information from pom.xml
        run: |
         echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls/pom.xml)"
         echo $version

      - name: Generate artifact name           
        run: |
         echo "##[set-env name=artifactName;]arm-oraclelinux-wls-$version-arm-assembly" 
         echo $artifactName
      - name: Output artifact name and path
        id: artifact_file
        run: |
         echo "##[set-output name=artifactName;]arm-oraclelinux-wls-$version-arm-assembly"
         echo "##[set-output name=artifactPath;]arm-oraclelinux-wls/target/$artifactName"
      
      - name: Unzip the package as upload action will zip again 
        if: success()
        run: unzip arm-oraclelinux-wls/target/$artifactName.zip -d arm-oraclelinux-wls/target/$artifactName
        
      - name: Archive ${{steps.artifact_file.outputs.artifactName}}.zip
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.artifact_file.outputs.artifactName}}
          path: ${{steps.artifact_file.outputs.artifactPath}}